### ISSUE TITLE
Add Event的两个方法区别

### ISSUE THREAD

**Issue by narakai** [CNAD666/book_manage#1]
BlocProvider.of<HomeBloc>(context)或者context.read()<HomeBloc>() (就是context.bloc<HomeBloc>()) 都可以add event，请问这两个有啥区别呢？

**Comment by CNAD666** [comment]
> BlocProvider.of(context)



> BlocProvider.of(context)或者context.read()() (就是context.bloc()) 都可以add event，请问这两个有啥区别呢？

没啥区别BlocProvider.of(context)一般可以添加一些初始化事件
相关使用可以看看这个：https://juejin.cn/post/6856268776510504968

**Comment by narakai** [comment]
好的，感谢回复
